package uz.pdp.bitcoin.util;

public interface BotState {
    String MENU_SEND="MENU_SEND";
    String MENU_EDIT="MENU_EDIT";
    String CHANGE_LANGUAGE_SEND="CHANGE_LANGUAGE_SEND";
    String CHANGE_LANGUAGE_EDIT="CHANGE_LANGUAGE_EDIT";

    String BALANCE="BALANCE";
    String STATISTICS="STATISTICS";
    String LAST_ONE="LAST_ONE";
    String LAST_24="LAST_24";
    String ALL_TIME="ALL_TIME";
    String HIGH="HIGH";
    String LOW="LOW";


    String PROFIT="PROFIT";
    String INVESTMENT_EDIT="INVESTMENT_EDIT";
    String INVESTMENT_SEND="INVESTMENT_SEND";
    String BITCOIN="BITCOIN";
    String SETTINGS = "SETTINGS";
    String MANAGEMENT_EDIT="MANAGEMENT_EDIT";
    String MANAGEMENT_SEND="MANAGEMENT_SEND";
    String GIVE_MOST_EDIT="GIVE_MOST_EDIT";
    String GIVE_LEAST_EDIT="GIVE_LEAST_EDIT";
    String GIVE_MOST_SEND="GIVE_MOST_SEND";
    String GIVE_LEAST_SEND="GIVE_LEAST_SEND";
    String STOP_NOTIFICATION="STOP_NOTIFICATION";

    String DYNAMIC_NOTIFICATION="DYNAMIC_NOTIFICATION";
    String SEND_MAIL_MESSAGE="SEND_MAIL_MESSAGE";
}
